stages:
  prepare_data:
    cmd: python dataset.py
    deps:
    - data/articles.csv
    - data/articles_mapping.json
    - data/customers.csv
    - data/customers_mapping.json
    - data/transactions_train.csv
    outs:
    - data/interaction_matrix/data.npz
  mf:
    cmd: python mf.py
    deps:
    - data/interaction_matrix/data.npz
    params:
    - mf.embedding_dim
    - mf.regularization
    metrics:
    - metrics/mf.json:
        cache: true
